[hint]
charsets = [
    [
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "2",
    "3",
    "4",
    "6",
    "7",
    "8",
    "9",
],
    [
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "2",
    "3",
    "4",
    "6",
    "7",
    "8",
    "9",
],
]
charset_extra = [
    "=",
    "-",
]

[hint.types.default]
style = "{background-color: rgba(66, 133, 244, 1); color: black; font-size: 11px;}"
z_index = 0

[hint.types.text]
style = "{background-color: rgba(66, 133, 244, 1); color: black; font-size: 11px;}"
z_index = 1

[hint.types.window]
style = """
{background-color: rgba(223, 8, 252, 1); 
color: white; font-size: 13px;
}"""
z_index = 5

[hint.types.pane]
style = "{background-color: rgba(67, 7, 231, 1); color: white; font-size: 12px;}"
z_index = 1

[hint.types.tab]
style = "{background-color: rgba(225, 240, 22, 1); color: black; font-size: 11px;}"
z_index = 2

[hint.types.button]
style = "{background-color: rgba(66, 133, 244, 1); color: black; font-size: 11px;}"
z_index = 4

[hint.types.scrollbar]
style = "{background-color: rgba(19, 148, 30, 1); color: black; font-size: 11px;}"
z_index = 3

[keybinding]
hotkey_buoy = "Alt+H"

[keybinding.global]
move_to_hint = ["HintKey"]
move_to_hint_exit = []
left_click_exit = [
    "HintKey",
    "Space",
]
hold_at_hint = [
    "HintKey",
    "Space",
]
exit = ["Esc"]

[keybinding.global.translate]
up = ["Up"]
down = ["Down"]
left = ["Left"]
right = ["Right"]

[keybinding.at_hint]
exit = ["Esc"]
left_click = ["LShift"]
left_click_exit = ["HintLeftKey"]
double_click = ["Enter"]
double_click_exit = []
right_click = ["RShift"]
right_click_exit = ["HintRightKey"]
middle_click = []
middle_click_exit = ["`"]

[keybinding.at_hint.translate]
up = []
down = []
left = []
right = []

[keybinding.at_hint.drag]
up = ["Up"]
down = ["Down"]
left = ["Left"]
right = ["Right"]

[keybinding.at_hint.scroll]
up = [
    "I",
    "E",
]
down = [
    "K",
    "D",
]
left = [
    "J",
    "S",
]
right = [
    "L",
    "F",
]

[[mouse.step.translate]]
x = 10
y = 10

[[mouse.step.translate]]
x = 50
y = 50
modifier = [
    "Tab",
    '\',
]

[[mouse.step.scroll]]
x = 120
y = -120

[[mouse.step.scroll]]
x = 600
y = -600
modifier = [
    "Tab",
    '\',
]

[[mouse.step.drag]]
x = 10
y = 10

[[mouse.step.drag]]
x = 50
y = 50
modifier = [
    "Tab",
    '\',
]

[keyboard]
propagation_modifier = [
    "LCtrl",
    "RCtrl",
    "LAlt",
    "RAlt",
    "LWin",
]

[keyboard.available_key]
F4 = 115
Num8 = 104
Num9 = 105
NumMultiply = 106
F9 = 120
RAlt = 165
Insert = 45
Num0 = 96
Num1 = 97
Esc = 27
Back = 8
F5 = 116
Delete = 46
Num5 = 101
F7 = 118
F2 = 113
NumDivide = 111
Space = 32
Right = 39
Num7 = 103
F10 = 121
F8 = 119
Up = 38
F1 = 112
Num4 = 100
Down = 40
NumAdd = 107
LWin = 91
LShift = 160
F6 = 117
PageDown = 34
NumSubtract = 109
Tab = 9
Backspace = 8
F3 = 114
CapsLock = 20
Num6 = 102
PageUp = 33
Enter = 13
RCtrl = 163
Num3 = 99
F11 = 122
LAlt = 164
F12 = 123
RShift = 161
LCtrl = 162
Left = 37
NumDecimal = 110
Home = 36
RWin = 92
End = 35
Num2 = 98

[keyboard.map_left_right.0]
left = "9"
right = "-"

[keyboard.map_left_right.1]
left = "`"
right = "2"

[keyboard.map_left_right.2]
left = "1"
right = "3"

[keyboard.map_left_right.3]
left = "2"
right = "4"

[keyboard.map_left_right.4]
left = "3"
right = "5"

[keyboard.map_left_right.5]
left = "4"
right = "6"

[keyboard.map_left_right.6]
left = "5"
right = "7"

[keyboard.map_left_right.7]
left = "6"
right = "8"

[keyboard.map_left_right.8]
left = "7"
right = "9"

[keyboard.map_left_right.9]
left = "8"
right = "0"

[keyboard.map_left_right."`"]
right = "1"

[keyboard.map_left_right.-]
left = "0"
right = "="

[keyboard.map_left_right."="]
left = "-"

[keyboard.map_left_right.Q]
right = "W"

[keyboard.map_left_right.W]
left = "Q"
right = "E"

[keyboard.map_left_right.E]
left = "W"
right = "R"

[keyboard.map_left_right.R]
left = "E"
right = "T"

[keyboard.map_left_right.T]
left = "R"
right = "Y"

[keyboard.map_left_right.Y]
left = "T"
right = "U"

[keyboard.map_left_right.U]
left = "Y"
right = "I"

[keyboard.map_left_right.I]
left = "U"
right = "O"

[keyboard.map_left_right.O]
left = "I"
right = "P"

[keyboard.map_left_right.P]
left = "O"
right = "["

[keyboard.map_left_right."["]
left = "P"
right = "]"

[keyboard.map_left_right."]"]
left = "["
right = '\'

[keyboard.map_left_right.'\']
left = "]"

[keyboard.map_left_right.A]
right = "S"

[keyboard.map_left_right.S]
left = "A"
right = "D"

[keyboard.map_left_right.D]
left = "S"
right = "F"

[keyboard.map_left_right.F]
left = "D"
right = "G"

[keyboard.map_left_right.G]
left = "F"
right = "H"

[keyboard.map_left_right.H]
left = "G"
right = "J"

[keyboard.map_left_right.J]
left = "H"
right = "K"

[keyboard.map_left_right.K]
left = "J"
right = "L"

[keyboard.map_left_right.L]
left = "K"
right = ";"

[keyboard.map_left_right.";"]
left = "L"
right = "'"

[keyboard.map_left_right."'"]
left = ";"
right = "/"

[keyboard.map_left_right.Z]
right = "X"

[keyboard.map_left_right.X]
left = "Z"
right = "C"

[keyboard.map_left_right.C]
left = "X"
right = "V"

[keyboard.map_left_right.V]
left = "C"
right = "B"

[keyboard.map_left_right.B]
left = "V"
right = "N"

[keyboard.map_left_right.N]
left = "B"
right = "M"

[keyboard.map_left_right.M]
left = "N"
right = ","

[keyboard.map_left_right.","]
left = "M"
right = "."

[keyboard.map_left_right."."]
left = ","
right = "/"

[keyboard.map_left_right."/"]
left = "."

[system]
start_in_tray = false
show_tray_icon = true
start_at_login = true

[ui_automation]
collect_interval = 1000
